# Generated by Django 5.2 on 2025-04-19 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Краткое описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='olympiad_covers/', verbose_name='Изображение')),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время начала')),
                ('end_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время окончания')),
                ('is_open', models.BooleanField(default=True, help_text='Если отмечено, любой пользователь может принять участие', verbose_name='Открытая')),
                ('time_limit_minutes', models.PositiveIntegerField(default=0, help_text='0 означает без ограничения', verbose_name='Ограничение по времени (мин)')),
                ('min_passing_score', models.PositiveIntegerField(default=0, verbose_name='Минимальный проходной балл')),
                ('invitation_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Код приглашения')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликована'), ('active', 'Активна'), ('completed', 'Завершена'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус')),
                ('is_rated', models.BooleanField(default=True, help_text='Влияет ли на общий рейтинг пользователей', verbose_name='Рейтинговая')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Олимпиада',
                'verbose_name_plural': 'Олимпиады',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='OlympiadCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=255, unique=True, verbose_name='Номер сертификата')),
                ('certificate_file', models.FileField(upload_to='olympiad_certificates/', verbose_name='Файл сертификата')),
                ('issue_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
            ],
            options={
                'verbose_name': 'Сертификат олимпиады',
                'verbose_name_plural': 'Сертификаты олимпиад',
            },
        ),
        migrations.CreateModel(
            name='OlympiadInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='00000000000000000000000000000000', max_length=32, unique=True, verbose_name='Код приглашения')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 означает без ограничений', verbose_name='Максимальное количество использований')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Использовано')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок действия до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Приглашение на олимпиаду',
                'verbose_name_plural': 'Приглашения на олимпиаду',
            },
        ),
        migrations.CreateModel(
            name='OlympiadMultipleChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст варианта')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('explanation', models.TextField(blank=True, verbose_name='Пояснение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['task', 'order'],
            },
        ),
        migrations.CreateModel(
            name='OlympiadParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Набранные баллы')),
                ('max_score', models.PositiveIntegerField(default=0, verbose_name='Максимальные баллы')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершил')),
                ('passed', models.BooleanField(default=False, verbose_name='Сдал')),
            ],
            options={
                'verbose_name': 'Участие в олимпиаде',
                'verbose_name_plural': 'Участия в олимпиадах',
            },
        ),
        migrations.CreateModel(
            name='OlympiadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Условие задачи')),
                ('task_type', models.CharField(choices=[('programming', 'Программирование'), ('multiple_choice', 'Тест с выбором ответа'), ('theoretical', 'Теоретический вопрос')], max_length=20, verbose_name='Тип задания')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Баллы')),
                ('time_limit_minutes', models.PositiveIntegerField(default=0, help_text='0 означает без ограничения', verbose_name='Ограничение по времени (мин)')),
                ('memory_limit_mb', models.PositiveIntegerField(default=0, help_text='0 означает без ограничения', verbose_name='Ограничение по памяти (МБ)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('min_passing_score', models.PositiveIntegerField(default=0, verbose_name='Минимальный проходной балл')),
                ('max_attempts', models.PositiveIntegerField(default=0, help_text='0 означает без ограничения', verbose_name='Максимальное количество попыток')),
                ('initial_code', models.TextField(blank=True, help_text='Код, который будет предоставлен участнику в начале', verbose_name='Начальный код')),
                ('topic', models.CharField(blank=True, help_text='Тематика задания для группировки', max_length=255, verbose_name='Тема')),
                ('difficulty', models.PositiveSmallIntegerField(default=1, help_text='Уровень сложности от 1 до 5', verbose_name='Сложность')),
                ('use_markdown', models.BooleanField(default=True, help_text='Отображать описание с поддержкой Markdown', verbose_name='Использовать Markdown')),
                ('use_latex', models.BooleanField(default=False, help_text='Включить поддержку математических формул в формате LaTeX', verbose_name='Использовать LaTeX')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Задание олимпиады',
                'verbose_name_plural': 'Задания олимпиад',
                'ordering': ['olympiad', 'order'],
            },
        ),
        migrations.CreateModel(
            name='OlympiadTaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, verbose_name='Код решения')),
                ('text_answer', models.TextField(blank=True, verbose_name='Текстовый ответ')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Набранные баллы')),
                ('max_score', models.PositiveIntegerField(default=0, verbose_name='Максимальные баллы')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильное решение')),
                ('passed_test_cases', models.PositiveIntegerField(default=0, verbose_name='Пройдено тестов')),
                ('total_test_cases', models.PositiveIntegerField(default=0, verbose_name='Всего тестов')),
                ('execution_time', models.FloatField(default=0, verbose_name='Время выполнения (сек)')),
                ('memory_usage', models.FloatField(default=0, verbose_name='Использовано памяти (МБ)')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
            ],
            options={
                'verbose_name': 'Отправка решения',
                'verbose_name_plural': 'Отправки решений',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='OlympiadTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(verbose_name='Входные данные')),
                ('expected_output', models.TextField(verbose_name='Ожидаемый результат')),
                ('is_hidden', models.BooleanField(default=False, help_text='Если отмечено, данные теста не будут видны участнику', verbose_name='Скрытый тест')),
                ('explanation', models.TextField(blank=True, verbose_name='Пояснение')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Баллы за прохождение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Тестовый случай',
                'verbose_name_plural': 'Тестовые случаи',
                'ordering': ['task', 'order'],
            },
        ),
        migrations.CreateModel(
            name='OlympiadUserInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Принято')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Приглашение пользователю',
                'verbose_name_plural': 'Приглашения пользователям',
            },
        ),
    ]
