# Generated by Django 5.2 on 2025-04-19 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_initial'),
        ('olympiads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_olympiads', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='related_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olympiads', to='courses.course', verbose_name='Связанный курс'),
        ),
        migrations.AddField(
            model_name='olympiadinvitation',
            name='olympiad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='olympiads.olympiad', verbose_name='Олимпиада'),
        ),
        migrations.AddField(
            model_name='olympiadparticipation',
            name='olympiad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='olympiads.olympiad', verbose_name='Олимпиада'),
        ),
        migrations.AddField(
            model_name='olympiadparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olympiad_participations', to=settings.AUTH_USER_MODEL, verbose_name='Участник'),
        ),
        migrations.AddField(
            model_name='olympiadcertificate',
            name='participation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='olympiads.olympiadparticipation', verbose_name='Участие'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='participants',
            field=models.ManyToManyField(related_name='olympiads', through='olympiads.OlympiadParticipation', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='olympiadtask',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olympiad_tasks', to='courses.course', verbose_name='Связанный курс'),
        ),
        migrations.AddField(
            model_name='olympiadtask',
            name='olympiad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='olympiads.olympiad', verbose_name='Олимпиада'),
        ),
        migrations.AddField(
            model_name='olympiadmultiplechoiceoption',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='olympiads.olympiadtask', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='olympiadtasksubmission',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='olympiads.olympiadparticipation', verbose_name='Участие'),
        ),
        migrations.AddField(
            model_name='olympiadtasksubmission',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='olympiads.olympiadmultiplechoiceoption', verbose_name='Выбранные варианты'),
        ),
        migrations.AddField(
            model_name='olympiadtasksubmission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='olympiads.olympiadtask', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='olympiadtestcase',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='olympiads.olympiadtask', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='olympiaduserinvitation',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_olympiad_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Пригласил'),
        ),
        migrations.AddField(
            model_name='olympiaduserinvitation',
            name='olympiad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invitations', to='olympiads.olympiad', verbose_name='Олимпиада'),
        ),
        migrations.AddField(
            model_name='olympiaduserinvitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olympiad_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='olympiadparticipation',
            unique_together={('olympiad', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='olympiaduserinvitation',
            unique_together={('olympiad', 'user')},
        ),
    ]
