# Generated by Django 5.2 on 2025-04-19 15:33

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID сертификата')),
                ('certificate_type', models.CharField(choices=[('course', 'Курс'), ('olympiad', 'Олимпиада'), ('achievement', 'Достижение')], default='course', max_length=20, verbose_name='Тип сертификата')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('active', 'Действителен'), ('revoked', 'Отозван'), ('expired', 'Истек')], default='active', max_length=20, verbose_name='Статус')),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выдачи')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата истечения')),
                ('earned_points', models.PositiveIntegerField(default=0, verbose_name='Набрано баллов')),
                ('max_points', models.PositiveIntegerField(default=100, verbose_name='Максимум баллов')),
                ('completion_percentage', models.FloatField(default=0, verbose_name='Процент выполнения')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdf/', verbose_name='PDF-файл')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='certificates/qr_codes/', verbose_name='QR-код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('template_type', models.CharField(choices=[('course', 'Курс'), ('olympiad', 'Олимпиада'), ('achievement', 'Достижение')], default='course', max_length=20, verbose_name='Тип шаблона')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='certificate_templates/backgrounds/', verbose_name='Фоновое изображение')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='certificate_templates/logos/', verbose_name='Логотип')),
                ('title_color', models.CharField(default='#1a1a1a', max_length=20, verbose_name='Цвет заголовка')),
                ('text_color', models.CharField(default='#333333', max_length=20, verbose_name='Цвет текста')),
                ('title_font_size', models.PositiveSmallIntegerField(default=48, verbose_name='Размер шрифта заголовка')),
                ('text_font_size', models.PositiveSmallIntegerField(default=24, verbose_name='Размер шрифта текста')),
                ('recipient_name_font_size', models.PositiveSmallIntegerField(default=36, verbose_name='Размер шрифта имени получателя')),
                ('title_text', models.CharField(default='СЕРТИФИКАТ', max_length=100, verbose_name='Текст заголовка')),
                ('subtitle_text', models.CharField(blank=True, max_length=200, verbose_name='Текст подзаголовка')),
                ('footer_text', models.CharField(default='© Образовательная платформа, 2025', max_length=200, verbose_name='Текст футера')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Шаблон сертификата',
                'verbose_name_plural': 'Шаблоны сертификатов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='course_covers/', verbose_name='Обложка курса')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('enable_certificates', models.BooleanField(default=True, verbose_name='Выдавать сертификаты')),
                ('min_points_for_certificate', models.PositiveIntegerField(default=70, help_text='Минимальное количество баллов, необходимое для получения сертификата', verbose_name='Минимальный балл для сертификата')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Начальный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый'), ('expert', 'Экспертный')], default='beginner', max_length=20, verbose_name='Уровень сложности')),
                ('duration_hours', models.PositiveIntegerField(default=0, help_text='Оценочная продолжительность курса в часах', verbose_name='Продолжительность (часы)')),
                ('tags', models.CharField(blank=True, help_text='Теги курса, разделенные запятыми', max_length=255, verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата завершения')),
                ('earned_points', models.PositiveIntegerField(default=0, verbose_name='Набранные баллы')),
                ('max_points', models.PositiveIntegerField(default=0, verbose_name='Максимальные баллы')),
                ('percentage', models.FloatField(default=0, verbose_name='Процент выполнения')),
                ('feedback', models.TextField(blank=True, verbose_name='Отзыв о курсе')),
                ('rating', models.PositiveSmallIntegerField(default=0, help_text='Оценка курса пользователем от 0 до 5', verbose_name='Оценка курса (0-5)')),
                ('certificate_generated', models.BooleanField(default=False, verbose_name='Сертификат выдан')),
            ],
            options={
                'verbose_name': 'Завершение курса',
                'verbose_name_plural': 'Завершения курсов',
                'ordering': ['-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата зачисления')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('progress', models.FloatField(default=0, verbose_name='Прогресс')),
            ],
            options={
                'verbose_name': 'Зачисление',
                'verbose_name_plural': 'Зачисления',
                'ordering': ['-enrolled_at'],
            },
        ),
    ]
