# Generated by Django 5.2 on 2025-04-19 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('olympiads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='olympiad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='olympiads.olympiad', verbose_name='Олимпиада'),
        ),
    ]
