# Generated by Django 5.2 on 2025-04-19 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_all', models.BooleanField(default=True, verbose_name='Получать все уведомления')),
                ('notify_only_high_priority', models.BooleanField(default=False, verbose_name='Получать только важные уведомления')),
                ('receive_achievement', models.BooleanField(default=True, verbose_name='Уведомления о достижениях')),
                ('receive_course', models.BooleanField(default=True, verbose_name='Уведомления о курсах')),
                ('receive_lesson', models.BooleanField(default=True, verbose_name='Уведомления об уроках')),
                ('receive_assignment', models.BooleanField(default=True, verbose_name='Уведомления о заданиях')),
                ('receive_message', models.BooleanField(default=True, verbose_name='Уведомления о сообщениях')),
                ('receive_system', models.BooleanField(default=True, verbose_name='Системные уведомления')),
                ('receive_deadline', models.BooleanField(blank=True, default=True, null=True, verbose_name='Уведомления о дедлайнах')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email-уведомления')),
                ('email_digest', models.BooleanField(default=False, verbose_name='Получать дайджест вместо отдельных писем')),
                ('push_notifications', models.BooleanField(default=False, verbose_name='Push-уведомления')),
                ('quiet_hours_enabled', models.BooleanField(default=False, verbose_name='Включить тихие часы')),
                ('quiet_hours_start', models.TimeField(blank=True, default='22:00', null=True, verbose_name='Начало тихих часов')),
                ('quiet_hours_end', models.TimeField(blank=True, default='08:00', null=True, verbose_name='Конец тихих часов')),
                ('weekdays_only', models.BooleanField(default=False, verbose_name='Только по будням')),
                ('weekend_only', models.BooleanField(default=False, verbose_name='Только по выходным')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('notification_type', models.CharField(choices=[('info', 'Информация'), ('success', 'Успех'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('achievement', 'Достижение'), ('course', 'Курс'), ('lesson', 'Урок'), ('assignment', 'Задание'), ('message', 'Сообщение')], default='info', max_length=20, verbose_name='Тип уведомления')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('is_high_priority', models.BooleanField(default=False, verbose_name='Высокий приоритет')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL')),
                ('importance', models.CharField(default='normal', max_length=20, verbose_name='Важность')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Иконка')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
    ]
