# Generated by Django 5.2 on 2025-04-19 17:19

import lessons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=lessons.models.LessonContent.get_upload_path, verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=lessons.models.LessonContent.get_upload_path, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='content_type',
            field=models.CharField(choices=[('text', 'Текст'), ('code', 'Код'), ('video', 'Видео'), ('assignment', 'Задание'), ('markdown', 'Markdown'), ('file', 'Файл'), ('image', 'Изображение')], max_length=20, verbose_name='Тип содержимого'),
        ),
    ]
